### ISSUE TITLE
Complete READMEs

### ISSUE THREAD

**Issue by codeMonkeyWebCoder** [codeMonkeyWebCoder/Rust-Blockchain#2]
How do you implement concurrency in Rust?

**Comment by coderm73** [comment]
Concurrency in Rust is primarily implemented using the ownership system to ensure that data races are impossible at compile time. Rust offers several tools for concurrent programming, such as threads, channels, and asynchronous programming via the `async/await` syntax. Here’s a rundown of how to implement concurrency in Rust:

### 1. **Using Threads**
Rust’s standard library provides a simple way to spawn threads using the `std::thread` module.

```rust
use std::thread;

fn main() {
    let handle = thread::spawn(|| {
        for i in 1..10 {
            println!("Hello from the spawned thread: {}", i);
            // simulate some work
            thread::sleep(std::time::Duration::from_millis(50));
        }
    });

    for i in 1..5 {
        println!("Hello from the main thread: {}", i);
        thread::sleep(std::time::Duration::from_millis(100));
    }

    // Wait for the spawned thread to finish
    handle.join().unwrap();
}
```

### 2. **Sharing Data Between Threads**
Rust uses the `Arc` (Atomic Reference Counting) type along with `Mutex` or `RwLock` to safely share data between threads.

#### Example with `Arc` and `Mutex`:
```rust
use std::sync::{Arc, Mutex};
use std::thread;

fn main() {
    let data = Arc::new(Mutex::new(0));
    let mut handles = vec![];

    for _ in 0..10 {
        let data = Arc::clone(&data);
        let handle = thread::spawn(move || {
            let mut num = data.lock().unwrap();
            *num += 1;
        });
        handles.push(handle);
    }

    for handle in handles {
        handle.join().unwrap();
    }

    println!("Result: {}", *data.lock().unwrap());
}
```
- `Arc<T>` allows safe shared ownership of the data.
- `Mutex<T>` ensures that only one thread can access the data at a time.

### 3. **Message Passing with Channels**
Rust has channels to enable message passing between threads, which is another common way to implement concurrency.

```rust
use std::sync::mpsc;
use std::thread;

fn main() {
    let (tx, rx) = mpsc::channel();

    thread::spawn(move || {
        let val = String::from("Hello from thread!");
        tx.send(val).unwrap();
    });

    let received = rx.recv().unwrap();
    println!("Received: {}", received);
}
```
- `mpsc` stands for "multiple producer, single consumer."
- Channels provide a way for threads to communicate by sending messages.

### 4. **Asynchronous Programming with `async/await`**
Rust’s async programming model is based on the `async` and `await` keywords, allowing for writing asynchronous code that looks like synchronous code.

#### Example with async:
```rust
use tokio; // An async runtime
use std::time::Duration;

async fn say_hello() {
    println!("Hello, world!");
}

#[tokio::main]
async fn main() {
    let task1 = tokio::spawn(async {
        say_hello().await;
    });

    let task2 = tokio::spawn(async {
        tokio::time::sleep(Duration::from_millis(500)).await;
        println!("Delayed hello");
    });

    task1.await.unwrap();
    task2.await.unwrap();
}
```
- The `tokio` crate is one of the most popular asynchronous runtimes.
- `async fn` defines an asynchronous function, and `await` is used to yield control until the future is ready.

### Key Takeaways
- **Threads:** Low-level, ideal for fine-grained control.
- **Channels:** Safe communication between threads, suitable for passing data.
- **Arc/Mutex:** For safe, concurrent data access.
- **Async/Await:** High-level, scalable, and more efficient for I/O-bound tasks.

Rust’s ownership model and type system ensure that concurrency bugs like data races are caught at compile time, making it a very safe choice for concurrent programming.
